#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled
sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
                try_files \$uri \$uri/ =404;
        }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
