#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled
sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
