#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "12i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo nginx -t
sudo service nginx restart
